CREATE TABLE aircraft_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    manufacturer VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    cruise_speed_km_h DOUBLE PRECISION NOT NULL,
    maximum_range_km DOUBLE PRECISION NOT NULL,
    fuel_capacity_litres DOUBLE PRECISION NOT NULL,
    fuel_consumption_litres_per_km DOUBLE PRECISION NOT NULL,
    passenger_capacity INTEGER NOT NULL,
    fuel_consumption_per_passenger DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_aircraft_types PRIMARY KEY (id),
    CONSTRAINT uq_aircraft_types_manufacturer_model UNIQUE (manufacturer, model),
    CONSTRAINT ck_aircraft_types_manufacturer CHECK (CHAR_LENGTH(TRIM(manufacturer)) > 0),
    CONSTRAINT ck_aircraft_types_model CHECK (CHAR_LENGTH(TRIM(model)) > 0),
    CONSTRAINT ck_aircraft_types_cruise_speed CHECK (cruise_speed_km_h > 0),
    CONSTRAINT ck_aircraft_types_maximum_range CHECK (maximum_range_km > 0),
    CONSTRAINT ck_aircraft_types_fuel_capacity CHECK (fuel_capacity_litres > 0),
    CONSTRAINT ck_aircraft_types_fuel_consumption CHECK (fuel_consumption_litres_per_km > 0),
    CONSTRAINT ck_aircraft_types_passenger_capacity CHECK (passenger_capacity > 0),
    CONSTRAINT ck_aircraft_types_fuel_per_passenger CHECK (fuel_consumption_per_passenger > 0)
);

CREATE TABLE flight_companies (
    code VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    base_airport_code VARCHAR(3) NOT NULL,
    CONSTRAINT pk_flight_companies PRIMARY KEY (code),
    CONSTRAINT ck_flight_companies_code CHECK (CHAR_LENGTH(TRIM(code)) > 0),
    CONSTRAINT ck_flight_companies_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT ck_flight_companies_country CHECK (CHAR_LENGTH(TRIM(country)) > 0),
    CONSTRAINT ck_flight_companies_base_airport_code CHECK (
        CHAR_LENGTH(base_airport_code) = 3
        AND SUBSTRING(base_airport_code FROM 1 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(base_airport_code FROM 2 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(base_airport_code FROM 3 FOR 1) BETWEEN 'A' AND 'Z'
    )
);
