-- Built-in aircraft type reference data.
-- Prepared from the project's design-time source dataset; the application does not read Excel at runtime.
-- IDs 1-23 are stable project identifiers and may later be referenced by flight-service seed data.

INSERT INTO aircraft_types (
    id,
    manufacturer,
    model,
    cruise_speed_km_h,
    maximum_range_km,
    fuel_capacity_litres,
    fuel_consumption_litres_per_km,
    passenger_capacity,
    fuel_consumption_per_passenger
) VALUES
    (1, 'Airbus', 'A220-100', 828, 6700, 21805, 2.23, 135, 2.03),
    (2, 'Airbus', 'A220-300', 828, 6300, 21508, 2.54, 160, 1.88),
    (3, 'Airbus', 'A319neo', 829, 6950, 29659, 2.9, 160, 2.23),
    (4, 'Airbus', 'A320neo', 829, 6300, 26730, 3.02, 194, 1.83),
    (5, 'Airbus', 'A321neo', 829, 7400, 26730, 3.32, 244, 1.66),
    (6, 'Airbus', 'A321XLR', 863, 8700, 36419, 4.24, 244, 2.12),
    (7, 'Airbus', 'A330-800', 880, 15090, 139090, 7.05, 406, 2.94),
    (8, 'Airbus', 'A330-900', 880, 13334, 139090, 7.76, 460, 2.77),
    (9, 'Airbus', 'A350-900', 903, 15372, 141000, 8.1, 440, 2.49),
    (10, 'Airbus', 'A350-1000', 905, 16850, 168300, 9.25, 480, 2.43),
    (11, 'Airbus', 'A380', 903, 14800, 320000, 16.61, 853, 3.1),
    (12, 'Boeing', '737-7', 839, 7040, 25817, 2.5, 172, 1.72),
    (13, 'Boeing', '737-8', 839, 6480, 25817, 2.65, 210, 1.56),
    (14, 'Boeing', '737-9', 839, 6110, 25817, 2.8, 220, 1.51),
    (15, 'Boeing', '737-10', 839, 5740, 25800, 2.95, 230, 1.51),
    (16, 'Boeing', '787-8', 903, 13530, 126206, 6.78, 359, 2.73),
    (17, 'Boeing', '787-9', 903, 14010, 126372, 7.15, 420, 2.42),
    (18, 'Boeing', '787-10', 903, 11730, 126370, 7.75, 440, 2.31),
    (19, 'Boeing', '777-200ER', 892, 13890, 171170, 8.52, 440, 2.83),
    (20, 'Boeing', '777-200LR', 892, 15740, 181283, 8.8, 440, 2.92),
    (21, 'Boeing', '777-300ER', 892, 14685, 181280, 9.58, 550, 2.42),
    (22, 'Boeing', '777-8', 905, 17590, 197700, 8.62, 495, 2.18),
    (23, 'Boeing', '777-9', 905, 14820, 198000, 9.2, 539, 2.16);

-- V1 uses GENERATED BY DEFAULT AS IDENTITY. Advance the H2 identity after explicit stable IDs
-- so future generated test/application records cannot collide with IDs 1-23.
ALTER TABLE aircraft_types ALTER COLUMN id RESTART WITH 24;
