-- Built-in flight company reference data.
-- Prepared from the project's design-time source dataset; the application does not read Excel at runtime.
-- base_airport_code is an external airport-service identifier, not a cross-service foreign key.

INSERT INTO flight_companies (code, name, country, base_airport_code) VALUES
    ('A3', 'Aegean Airlines', 'Greece', 'ATH'),
    ('EI', 'Aer Lingus', 'Ireland', 'DUB'),
    ('SU', 'Aeroflot', 'Russia', 'SVO'),
    ('AR', 'Aerolineas Argentinas', 'Argentina', 'EZE'),
    ('AM', 'Aeromexico', 'Mexico', 'MEX'),
    ('KC', 'Air Astana', 'Kazakhstan', 'ALA'),
    ('BT', 'Air Baltic', 'Latvia', 'RIX'),
    ('AC', 'Air Canada', 'Canada', 'YYZ'),
    ('CA', 'Air China', 'China', 'PVG'),
    ('AF', 'Air France', 'France', 'CDG'),
    ('AI', 'Air India', 'India', 'DEL'),
    ('KM', 'Air Malta', 'Malta', 'MLA'),
    ('MK', 'Air Mauritius', 'Mauritius', 'MRU'),
    ('SW', 'Air Namibia', 'Namibia', 'WDH'),
    ('NZ', 'Air New Zealand', 'New Zealand', 'AKL'),
    ('JU', 'Air Serbia', 'Serbia', 'BEG'),
    ('NF', 'Air Vanuatu', 'Vanuatu', 'VLI'),
    ('AZ', 'Alitalia', 'Italy', 'FCO'),
    ('OS', 'Austrian', 'Austria', 'VIE'),
    ('AV', 'Avianca', 'Colombia', 'BOG'),
    ('J2', 'Azerbaijan Hava Yollary', 'Azerbaijan', 'GYD'),
    ('AD', 'Azul', 'Brazil', 'GRU'),
    ('BA', 'British Airways', 'United Kingdom', 'LHR'),
    ('SN', 'Brussels Airlines', 'Belgium', 'BRU'),
    ('BW', 'Caribbean Airlines', 'Trinidad and Tobago', 'POS'),
    ('CM', 'Copa Airlines', 'Panama', 'PTY'),
    ('OU', 'Croatia Airlines', 'Croatia', 'ZAG'),
    ('OK', 'Czech Airlines', 'Czechia', 'PRG'),
    ('DL', 'Delta', 'United States', 'ATL'),
    ('MS', 'Egyptair', 'Egypt', 'CAI'),
    ('LY', 'EL AL', 'Israel', 'TLV'),
    ('EK', 'Emirates', 'United Arab Emirates', 'DXB'),
    ('ET', 'Ethiopian Airlines', 'Ethiopia', 'ADD'),
    ('FJ', 'Fiji Airways', 'Fiji', 'NAN'),
    ('AY', 'Finnair', 'Finland', 'HEL'),
    ('5F', 'FlyOne', 'Moldova', 'RMO'),
    ('GA', 'Garuda Indonesia', 'Indonesia', 'CGK'),
    ('GF', 'Gulf Air', 'Bahrain', 'BAH'),
    ('IB', 'Iberia', 'Spain', 'MAD'),
    ('FI', 'Iceland Air', 'Iceland', 'KEF'),
    ('JL', 'Japan Airlines', 'Japan', 'HND'),
    ('KQ', 'Kenya Airways', 'Kenya', 'NBO'),
    ('KL', 'KLM', 'Netherlands', 'AMS'),
    ('KE', 'Korean Air', 'South Korea', 'ICN'),
    ('LA', 'LATAM', 'Chile', 'SCL'),
    ('LO', 'LOT Polish Airlines', 'Poland', 'WAW'),
    ('LH', 'Lufthansa', 'Germany', 'FRA'),
    ('LG', 'Luxair', 'Luxembourg', 'LUX'),
    ('MH', 'Malaysia Airlines', 'Malaysia', 'KUL'),
    ('ME', 'Middle East Airlines', 'Lebanon', 'BEY'),
    ('DY', 'Norwegian Air Shuttle', 'Norway', 'OSL'),
    ('LE', 'Norwegian Air Sweden', 'Sweden', 'ARN'),
    ('WY', 'Oman Air', 'Oman', 'MCT'),
    ('PK', 'Pakistan International Airlines', 'Pakistan', 'ISB'),
    ('PR', 'Philippine Airlines', 'Philippines', 'MNL'),
    ('QF', 'Qantas', 'Australia', 'SYD'),
    ('QR', 'Qatar Airways', 'Qatar', 'DOH'),
    ('AT', 'Royal Air Maroc', 'Morocco', 'CMN'),
    ('BI', 'Royal Brunei', 'Brunei', 'BWN'),
    ('RJ', 'Royal Jordanian', 'Jordan', 'AMM'),
    ('WB', 'RwandAir', 'Rwanda', 'KGL'),
    ('SK', 'SAS', 'Denmark', 'CPH'),
    ('SV', 'Saudia', 'Saudi Arabia', 'JED'),
    ('SQ', 'Singapore Airlines', 'Singapore', 'SIN'),
    ('SA', 'South African Airways', 'South Africa', 'JNB'),
    ('UL', 'SriLankan Airlines', 'Sri Lanka', 'CMB'),
    ('LX', 'SWISS', 'Switzerland', 'ZRH'),
    ('DT', 'TAAG', 'Angola', 'NBJ'),
    ('TA', 'TACA', 'El Salvador', 'SAL'),
    ('TP', 'TAP Portugal', 'Portugal', 'LIS'),
    ('TG', 'THAI', 'Thailand', 'BKK'),
    ('TU', 'Tunis Air', 'Tunisia', 'TUN'),
    ('TK', 'Turkish Airlines', 'Turkiye', 'IST'),
    ('PS', 'Ukraine International', 'Ukraine', 'KBP'),
    ('HY', 'Uzbekistan Airways', 'Uzbekistan', 'TAS'),
    ('VN', 'Vietnam Airlines', 'Vietnam', 'SGN'),
    ('W6', 'Wizzair', 'Hungary', 'BUD');
