CREATE TABLE company_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_number INTEGER NOT NULL,
    company_code VARCHAR(10) NOT NULL,
    base_airport_code VARCHAR(3) NOT NULL,
    destination_airport_code VARCHAR(3) NOT NULL,
    aircraft_type_id BIGINT NOT NULL,
    scheduled_outbound_departure_utc TIME NOT NULL,
    CONSTRAINT pk_company_routes PRIMARY KEY (id),
    CONSTRAINT uq_company_routes_company_route_number UNIQUE (company_code, route_number),
    CONSTRAINT ck_company_routes_route_number CHECK (route_number BETWEEN 1 AND 8),
    CONSTRAINT ck_company_routes_company_code CHECK (CHAR_LENGTH(TRIM(company_code)) > 0),
    CONSTRAINT ck_company_routes_base_airport_code CHECK (
        CHAR_LENGTH(base_airport_code) = 3
        AND SUBSTRING(base_airport_code FROM 1 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(base_airport_code FROM 2 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(base_airport_code FROM 3 FOR 1) BETWEEN 'A' AND 'Z'
    ),
    CONSTRAINT ck_company_routes_destination_airport_code CHECK (
        CHAR_LENGTH(destination_airport_code) = 3
        AND SUBSTRING(destination_airport_code FROM 1 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(destination_airport_code FROM 2 FOR 1) BETWEEN 'A' AND 'Z'
        AND SUBSTRING(destination_airport_code FROM 3 FOR 1) BETWEEN 'A' AND 'Z'
    ),
    CONSTRAINT ck_company_routes_distinct_airports CHECK (base_airport_code <> destination_airport_code),
    CONSTRAINT ck_company_routes_aircraft_type_id CHECK (aircraft_type_id > 0)
);
